apiVersion: v1
kind: Pod
metadata:
  name: go-netdisk
  labels:
    app: go
spec:
  containers:
    - name: go-netdisk
      image: feichaicom/go-netdisk:v1.0.6
      imagePullPolicy: IfNotPresent
      command: ["/start"]
      env:
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          value: "mysql://miya:66666666@mysql:3306/mydb"
        - name: GCS_MYSQL_NAME
          value: mydb
        - name: GCS_MYSQL_PORT
          value: "3306"
        - name: GCS_MYSQL_PASSWORD
          value: "66666666"
        - name: GCS_MYSQL_USER
          value: miya
        - name: GCS_MYSQL_HOST
          value: mysql
        - name: BKPAAS_ENVIRONMENT
          value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: go
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000 
      nodePort: 31080
  selector:
    app: go
  type: NodePort
