# default config

debug: true
port: 5000
logfile: "gin.log"
media-dir: "./media"
upload-dir: "./media/matter-root"
default-password: miya.12345

mysql:
  name: tank
  host: 127.0.0.1
  port: 3306
  username: root
  password: root

jwt:
  issuer: "FEICHAI.COM"
  secret-key: "feichaicom"
  auth-cookie-name: "auth_token"

login:
  ticket: BKAPP_TICKET
  login-url: BKAPP_LOGIN_URL
  user-info-url: BKAPP_USER_INFO_URL
  uid: BKAPP_UID
  sub-path: "/"
