# default config

debug: true
port: 5000
logfile: "gin.log"
mediadir: "./media"
default-password: miya.12345

mysql:
  name: tank
  host: 127.0.0.1
  port: 3306
  username: root
  password: root

jwt:
  issuer: "FEICHAI.COM"
  secret-key: "feichaicom"
  auth-cookie-name: "auth_token"

login:
  ticket: "bk_ticket"
  login-url: "http://login.o.abc.com/"
  user-info-url: "http://login.o.abc.com/user/get_full_info"
  uid: "bk_uid"
  sub-path: "/"
