# go-netdisk global config

gin:

database:
  dsn: "root:88888888@tcp(localhost:3306)/tank?charset=utf8mb4&parseTime=True&loc=Local"
  type: mysql
  username: root
  password: 88888888
  host: localhost
  port: 3306
  name: tank
  charset: utf8mb4
  parseTime: true
  loc: Local

