apiVersion: v1
kind: Service
metadata:
  name: go-netdisk
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 31080
  selector:
    app: go
    version: v1.0.0
  type: NodePort
