apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size | default "10Gi" | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  storageClassName: {{ .Values.persistence.storageClass }}
  mountOptions:
    - hard
  nfs:
    path: {{ .Values.persistence.nfsPath }}
    server: {{ .Values.persistence.nfsServer }}
