apiVersion: v1
data:
  mysqld.cnf: |
    [mysqld]
    max_connections = 200
    read_buffer_size = 1048576
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci

    [mysql]
    default-character-set=utf8mb4

    [client]
    default-character-set=utf8mb4
kind: ConfigMap
metadata:
  name: mysql-config
