apiVersion: v1
kind: Secret
type: Opaque
stringData:
  MYSQL_PORT: {{ .Values.mysql.port }}
  MYSQL_DATABASE: {{ .Values.mysql.database }}
  MYSQL_USER: {{ .Values.mysql.user }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
metadata:
  name: mysql-secret
