apiVersion: v1
kind: Secret
metadata:
  name: go-secret
type: Opaque
stringData:
  DATABASE_URL: mysql://miya:66666666@mysql:3306/mydb
#data:
  # echo xxx | base64 -d
  # DATABASE_URL: bXlzcWw6Ly9taXlhOjY2NjY2NjY2QG15c3FsOjMzMDYvbXlkYgo=
