apiVersion: v1
kind: Pod
metadata:
  name: go-netdisk
  labels:
    app: go
spec:
  containers:
    - name: go-netdisk
      image: feichaicom/go-netdisk:v1.1.2
      imagePullPolicy: IfNotPresent
      command: ["/start"]
      envFrom:
        - configMapRef:
            name: go-config
        - secretRef:
            name: go-secret
---
apiVersion: v1
kind: Service
metadata:
  name: go
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 31080
  selector:
    app: go
  type: NodePort
