apiVersion: v1
kind: Pod
metadata:
  name:
    mysql
  labels:
    app: mysql
spec:
  volumes:
    - name: data-volume
      hostPath:
        path: /data/mysql
        type: DirectoryOrCreate
    - name: config-volume
      configMap:
        name: mysql-config
        optional: true
  containers:
    - name: mysql57
      image: mysql:5.7
      envFrom:
        - configMapRef:
            name: mysql-config
        - secretRef:
            name: mysql-secret
      volumeMounts:
        - name: data-volume
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/conf.d
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: tcp
      port: 3306
      targetPort: 3306
  type: ClusterIP
