apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-netdisk.fullname" . }}
  labels:
    {{- include "go-netdisk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web-port
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "go-netdisk.selectorLabels" . | nindent 4 }}
    version: v1.0.0
