apiVersion: v1
kind: Secret
metadata:
  name: go-secret-{{ .Release.Name }}
type: Opaque
stringData:
  GCS_MYSQL_NAME: {{ .Values.mysql.database }}
  GCS_MYSQL_PORT: {{ .Values.mysql.port | quote }}
  GCS_MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  GCS_MYSQL_USER: {{ .Values.mysql.user }}
  GCS_MYSQL_HOST: mysql
  BKPAAS_ENVIRONMENT: prod
#data:
  # echo xxx | base64 -d
  # DATABASE_URL: bXlzcWw6Ly9taXlhOjY2NjY2NjY2QG15c3FsOjMzMDYvbXlkYgo=
